[2025-01-28T10:51:16.678+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-28T10:51:16.875+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: raw_api_sales_data.store_sales_data_raw manual__2025-01-28T10:50:41.106920+00:00 [queued]>
[2025-01-28T10:51:16.886+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: raw_api_sales_data.store_sales_data_raw manual__2025-01-28T10:50:41.106920+00:00 [queued]>
[2025-01-28T10:51:16.887+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-28T10:51:16.911+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): store_sales_data_raw> on 2025-01-28 10:50:41.106920+00:00
[2025-01-28T10:51:16.921+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4259) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-28T10:51:16.924+0000] {standard_task_runner.py:72} INFO - Started process 4261 to run task
[2025-01-28T10:51:16.924+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'raw_api_sales_data', 'store_sales_data_raw', 'manual__2025-01-28T10:50:41.106920+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/raw/dag_load_sales_data_to_db.py', '--cfg-path', '/tmp/tmpwebcm94g']
[2025-01-28T10:51:16.926+0000] {standard_task_runner.py:105} INFO - Job 153: Subtask store_sales_data_raw
[2025-01-28T10:51:16.992+0000] {task_command.py:467} INFO - Running <TaskInstance: raw_api_sales_data.store_sales_data_raw manual__2025-01-28T10:50:41.106920+00:00 [running]> on host 1de8b92bf5f9
[2025-01-28T10:51:17.116+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='raw_api_sales_data' AIRFLOW_CTX_TASK_ID='store_sales_data_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-01-28T10:50:41.106920+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-28T10:50:41.106920+00:00'
[2025-01-28T10:51:17.117+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-28T10:51:17.118+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-28T10:51:17.119+0000] {logging_mixin.py:190} INFO - Current task name:store_sales_data_raw state:running start_date:2025-01-28 10:51:16.876126+00:00
[2025-01-28T10:51:17.119+0000] {logging_mixin.py:190} INFO - Dag name:raw_api_sales_data and current dag run status:running
[2025-01-28T10:51:17.120+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-28T10:51:17.340+0000] {database_helpers.py:21} INFO - Connected to PostgreSQL database.
[2025-01-28T10:51:17.341+0000] {raw_store_sales_data.py:34} ERROR - Failed to insert data to a table : string indices must be integers, not 'str'
[2025-01-28T10:51:17.342+0000] {database_helpers.py:31} INFO - Closed the database connection.
[2025-01-28T10:51:17.343+0000] {raw_store_sales_data.py:38} INFO - Database Closed
[2025-01-28T10:51:17.344+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/logic/raw_store_sales_data.py", line 24, in store_api_sales_data
    d[columns[0]],d[columns[1]], d[columns[2]], d[columns[3]],
    ~^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2025-01-28T10:51:17.365+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-28T10:51:17.366+0000] {logging_mixin.py:190} INFO - Task start:2025-01-28 10:51:16.876126+00:00 end:2025-01-28 10:51:17.365010+00:00 duration:0.488884
[2025-01-28T10:51:17.367+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): store_sales_data_raw> dag:<DAG: raw_api_sales_data> dagrun:<DagRun raw_api_sales_data @ 2025-01-28 10:50:41.106920+00:00: manual__2025-01-28T10:50:41.106920+00:00, state:running, queued_at: 2025-01-28 10:50:41.926220+00:00. externally triggered: True>
[2025-01-28T10:51:17.367+0000] {logging_mixin.py:190} INFO - Failure caused by string indices must be integers, not 'str'
[2025-01-28T10:51:17.368+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=raw_api_sales_data, task_id=store_sales_data_raw, run_id=manual__2025-01-28T10:50:41.106920+00:00, execution_date=20250128T105041, start_date=20250128T105116, end_date=20250128T105117
[2025-01-28T10:51:17.387+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-28T10:51:17.390+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 153 for task store_sales_data_raw (string indices must be integers, not 'str'; 4261)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/logic/raw_store_sales_data.py", line 24, in store_api_sales_data
    d[columns[0]],d[columns[1]], d[columns[2]], d[columns[3]],
    ~^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2025-01-28T10:51:17.422+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-28T10:51:17.443+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-28T10:51:17.449+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
